version: '2'
services:
  web:
    image: lavoweb/php-8.2
    ports:
      - "88:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db:db
  db:
    image: mysql
    volumes:
      - /mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    links:
      - db:db
